site_name: 笔记
site_author: cht
theme:
    name: material
    feature:
        tabs: true
    language: 'zh'
    palette:
        primary: 'teal'
        accent: 'amber'
        scheme: 'slate'
    font:
        text: Ubuntu
        code: Ubuntu Mono
extra:
    search:
        language: 'zh'
markdown_extensions:
    - meta
    - admonition # 注解
    - pymdownx.details # 折叠需要的
    - footnotes # 脚注
    - pymdownx.critic # 强调
    - pymdownx.inlinehilite # 行内代码高亮
    - pymdownx.superfences # 注解嵌套代码块
    - pymdownx.smartsymbols # 特殊符号
    - codehilite # 代码高亮
    - toc:
        permalink: true
nav:
    - 主页:
        - 更新日志: index.md
    - 系统与工具:
        - ubuntu: notes/ubuntu.md
        - Windows: notes/windows.md    
    - 编程与开发:
        - web:
            - start: notes/web_start.md
            - struts2: notes/struts2.md
            - spring: notes/spring.md
            - Kotlin Web: notes/kotlin_web.md
            - asp.net core: notes/asp-web.md
        - api: notes/api.md
        - Android: 
            - 原生: notes/android.md
            - Flutter: notes/flutter.md
        - C++: notes/cpp.md
        - 后端教程: notes/backend_index.md
    - 杂项:
        - 文档规范: draft/regular.md
        - 资源整理: draft/resources.md 
markdown_extensions:
  - meta
  - admonition # 注解
  - pymdownx.details # 折叠需要的
  - footnotes # 脚注
  - pymdownx.critic # 强调
  - pymdownx.inlinehilite # 行内代码高亮
  - pymdownx.superfences # 注解嵌套代码块
  - pymdownx.smartsymbols # 特殊符号
  - codehilite # 代码高亮
  - toc:
      permalink: true