site_name: 个人笔记
site_author: cht
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'Blue'
    accent: 'Cyan'
extra:
    search:
        language: 'zh'
nav:
    - 主页: index.md
    - 编程笔记: 
        - Android Native: android_index.md
        - C++: cpp_index.md
        - Kotlin For Tomcat: kotlin_tomcat.md
        - 深度学习: deeplearning_index.md
    - 学科:
        - 英语:
            - 单词: english_word.md
    - 资源整理: resources.md
    - 开发文档:
        - 文档编写规范: regular.md
        - 用户系统API: doc_user.md

markdown_extensions:
  - admonition # 注解
  - pymdownx.details # 折叠需要的
  - footnotes # 脚注
  - pymdownx.critic # 强调
  - pymdownx.inlinehilite # 行内代码高亮
  - pymdownx.superfences # 注解嵌套代码块
  - pymdownx.smartsymbols # 特殊符号
  - codehilite # 代码高亮
  - toc:
      permalink: true