site_name: igrape
site_author: cht
theme:
    name: 'material'
    language: 'zh'
    palette:
        primary: 'Blue'
        accent: 'Cyan'
    feature:
        tabs: true
extra:
    search:
        language: 'zh'
nav:
    - 笔记:
        - Android: notes/android.md
        - C++: notes/cpp.md
        - Kotlin Web: notes/kotlin_web.md
        - 深度学习: notes/deeplearning_index.md
        - 后端教程: notes/backend_index.md
        - 英语单词: notes/english_word.md
        - ubuntu: notes/ubuntu.md
        - Windows: notes/windows.md
        - 整理文档: notes/archive_doc.md
    - 想法:
        - 主页: idea/index.md
    - 项目:
        - 项目: project/index.md
    - 杂项:
        - 动态: index.md
        - 文档规范: draft/regular.md
        - 资源整理: draft/resources.md
        

markdown_extensions:
  - meta
  - admonition # 注解
  - pymdownx.details # 折叠需要的
  - footnotes # 脚注
  - pymdownx.critic # 强调
  - pymdownx.inlinehilite # 行内代码高亮
  - pymdownx.superfences # 注解嵌套代码块
  - pymdownx.smartsymbols # 特殊符号
  - codehilite # 代码高亮
  - toc:
      permalink: true